name: Dockerfile Lint

on:
  pull_request:
    paths:
      - '**/Dockerfile'
  push:
    branches:
      - master
      - development

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        # Optional parameters based on your needs
        # config: .hadolint.yaml
        # no-color: false
        # verbose: false
        # failure-threshold: error
        # format: json

    - name: Run Hadolint
      run: |
        hadolint Dockerfile
      continue-on-error: false  # Ensure the job fails if Hadolint fails

