name: Dockerfile Lint

on:
  pull_request:
    paths:
      - '**/Dockerfile'
  push:
    branches:
      - master
      - development

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: error
        no-color: false

