name: Security Scans

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Snyk Maven Dependency Scan
      uses: snyk/actions/maven-3-jdk-17@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
      with:
        args: --severity-threshold=high --fail-on=all

