name: Secret Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run TruffleHog
      run: |
        docker run --rm trufflesecurity/trufflehog git --json --branch master https://github.com/NimrodBarOn/simple-java-maven-app

