name: Secret Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run TruffleHog
      run: |
        docker run --rm trufflesecurity/trufflehog:latest --json https://github.com/NimrodBarOn/simple-java-maven-app

