name: Versioning

on:
  workflow_run:
    workflows: ["Security Scans"]
    types:
      - completed

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Maven
      run: |
        MAVEN_VERSION=3.9.2
        wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
        tar xzvf apache-maven-$MAVEN_VERSION-bin.tar.gz
        sudo mv apache-maven-$MAVEN_VERSION /opt/maven
        sudo ln -sf /opt/maven/bin/mvn /usr/bin/mvn
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

    - name: Update Maven version
      id: update_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
          NEW_MINOR=$((MINOR+1))
          NEW_VERSION="$MAJOR.$NEW_MINOR.0"
        elif [[ $GITHUB_REF == 'refs/heads/development' ]]; then
          NEW_PATCH=$((PATCH+1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        else
          echo "Not a monitored branch. Skipping version increment."
          exit 0
        fi
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
        mvn versions:set -DnewVersion=$NEW_VERSION

    - name: Commit and push new version
      if: success()
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add pom.xml
        git commit -m "Update version to ${{ env.new_version }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

